-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GetFiveApi.Object.MatchPayload exposing (..)

import GetFiveApi.InputObject
import GetFiveApi.Interface
import GetFiveApi.Object
import GetFiveApi.Scalar
import GetFiveApi.ScalarCodecs
import GetFiveApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A list of failed validations. May be blank or null if mutation succeeded.
-}
messages :
    SelectionSet decodesTo GetFiveApi.Object.ValidationMessage
    -> SelectionSet (Maybe (List (Maybe decodesTo))) GetFiveApi.Object.MatchPayload
messages object____ =
    Object.selectionForCompositeField "messages" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| The object created/updated/deleted by the mutation. May be null if mutation failed.
-}
result :
    SelectionSet decodesTo GetFiveApi.Object.Match
    -> SelectionSet (Maybe decodesTo) GetFiveApi.Object.MatchPayload
result object____ =
    Object.selectionForCompositeField "result" [] object____ (identity >> Decode.nullable)


{-| Indicates if the mutation completed successfully or not.
-}
successful : SelectionSet Bool GetFiveApi.Object.MatchPayload
successful =
    Object.selectionForField "Bool" "successful" [] Decode.bool
