-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GetFiveApi.Object.Match exposing (..)

import GetFiveApi.Enum.MatchTeam
import GetFiveApi.Enum.SeriesType
import GetFiveApi.Enum.SideType
import GetFiveApi.InputObject
import GetFiveApi.Interface
import GetFiveApi.Object
import GetFiveApi.Scalar
import GetFiveApi.ScalarCodecs
import GetFiveApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


apiKey : SelectionSet String GetFiveApi.Object.Match
apiKey =
    Object.selectionForField "String" "apiKey" [] Decode.string


endTime : SelectionSet String GetFiveApi.Object.Match
endTime =
    Object.selectionForField "String" "endTime" [] Decode.string


enforceTeams : SelectionSet Bool GetFiveApi.Object.Match
enforceTeams =
    Object.selectionForField "Bool" "enforceTeams" [] Decode.bool


gameServer :
    SelectionSet decodesTo GetFiveApi.Object.GameServer
    -> SelectionSet decodesTo GetFiveApi.Object.Match
gameServer object____ =
    Object.selectionForCompositeField "gameServer" [] object____ identity


id : SelectionSet GetFiveApi.ScalarCodecs.Id GetFiveApi.Object.Match
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GetFiveApi.ScalarCodecs.codecs |> GetFiveApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


maxMaps : SelectionSet Int GetFiveApi.Object.Match
maxMaps =
    Object.selectionForField "Int" "maxMaps" [] Decode.int


minPlayerReady : SelectionSet Int GetFiveApi.Object.Match
minPlayerReady =
    Object.selectionForField "Int" "minPlayerReady" [] Decode.int


seriesType : SelectionSet GetFiveApi.Enum.SeriesType.SeriesType GetFiveApi.Object.Match
seriesType =
    Object.selectionForField "Enum.SeriesType.SeriesType" "seriesType" [] GetFiveApi.Enum.SeriesType.decoder


sideType : SelectionSet GetFiveApi.Enum.SideType.SideType GetFiveApi.Object.Match
sideType =
    Object.selectionForField "Enum.SideType.SideType" "sideType" [] GetFiveApi.Enum.SideType.decoder


spectatorIds : SelectionSet (Maybe (List (Maybe String))) GetFiveApi.Object.Match
spectatorIds =
    Object.selectionForField "(Maybe (List (Maybe String)))" "spectatorIds" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


startTime : SelectionSet String GetFiveApi.Object.Match
startTime =
    Object.selectionForField "String" "startTime" [] Decode.string


status : SelectionSet String GetFiveApi.Object.Match
status =
    Object.selectionForField "String" "status" [] Decode.string


team1 :
    SelectionSet decodesTo GetFiveApi.Object.Team
    -> SelectionSet decodesTo GetFiveApi.Object.Match
team1 object____ =
    Object.selectionForCompositeField "team1" [] object____ identity


team1Score : SelectionSet (Maybe Int) GetFiveApi.Object.Match
team1Score =
    Object.selectionForField "(Maybe Int)" "team1Score" [] (Decode.int |> Decode.nullable)


team2 :
    SelectionSet decodesTo GetFiveApi.Object.Team
    -> SelectionSet decodesTo GetFiveApi.Object.Match
team2 object____ =
    Object.selectionForCompositeField "team2" [] object____ identity


team2Score : SelectionSet (Maybe Int) GetFiveApi.Object.Match
team2Score =
    Object.selectionForField "(Maybe Int)" "team2Score" [] (Decode.int |> Decode.nullable)


title : SelectionSet String GetFiveApi.Object.Match
title =
    Object.selectionForField "String" "title" [] Decode.string


vetoFirst : SelectionSet GetFiveApi.Enum.MatchTeam.MatchTeam GetFiveApi.Object.Match
vetoFirst =
    Object.selectionForField "Enum.MatchTeam.MatchTeam" "vetoFirst" [] GetFiveApi.Enum.MatchTeam.decoder


vetoMapPool : SelectionSet (Maybe (List (Maybe String))) GetFiveApi.Object.Match
vetoMapPool =
    Object.selectionForField "(Maybe (List (Maybe String)))" "vetoMapPool" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


winner :
    SelectionSet decodesTo GetFiveApi.Object.Team
    -> SelectionSet (Maybe decodesTo) GetFiveApi.Object.Match
winner object____ =
    Object.selectionForCompositeField "winner" [] object____ (identity >> Decode.nullable)
