FROM elixir:1.15.7

RUN apt-get update && \
    apt-get install -y postgresql-client

RUN mix local.hex --force && \
    mix archive.install hex phx_new --force && \
    mix local.rebar --force

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# Cache elixir deps
ADD mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

CMD ["mix", "phx.server"]
