version: "3"
volumes:
  node_modules:
  build:
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
       - db-data:/var/lib/postgresql/data
  # web:
  #   image: bitwalker/alpine-elixir-phoenix
  #   env_file: .env
  #   command: mix phx.server
  #   volumes:
  #     - .:/opt/app
  #     - build:/opt/app/_build
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - db
  #   stdin_open: true
  #   tty: true

volumes:
  db-data: