version: "3"
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
       - db-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file: .env
    volumes:
      - ./:/app
      - /app/assets/node_modules
      - /app/deps
    ports:
      - "4000:4000"
      - "1234:1234"
    depends_on:
      - db


volumes:
  db-data:
