version: "3"
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
       - db-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file: .docker_env
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
      - "1234:1234"
    depends_on:
      - db
  # csgo:
  #   image: ghcr.io/ringvold/csgo
  #   environment:
  #     GITHUB_TOKEN: ""
  #     SERVER_HOSTNAME: "Get5API test server"
  #     SERVER_PASSWORD:
  #     RCON_PASSWORD: changeme
  #     STEAM_ACCOUNT: changeme
  #     AUTHKEY: changeme
  #     SOURCEMOD_ADMINS: comma,delimited,list,of,steam,ids
  #     IP: 0.0.0.0
  #     PORT: 27015
  #     TV_PORT: 27020
  #     TICKRATE: 128
  #     FPS_MAX: 300
  #     GAME_TYPE: 0
  #     GAME_MODE: 1
  #     MAP: de_dust2
  #     MAPGROUP: mg_active
  #     MAXPLAYERS: 12
  #     TV_ENABLE: 1
  #     LAN: 0



volumes:
  db-data:
