# fly.toml file generated for get5-api on 2021-09-01T00:02:30+02:00

app = "get5-api"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[deploy]
  release_command = "/app/bin/get5_api eval Get5Api.Release.migrate"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s" # allow some time for startup
    interval = "15s"
    restart_limit = 6
    timeout = "2s"