# fly.toml file generated for get5-api on 2021-09-01T00:02:30+02:00

app = "get5-api"
primary_region = 'ams'
kill_signal = 'SIGTERM'

[env]
  PHX_HOST = 'get5-api.fly.dev'
  PORT = '8080'

[deploy]
  release_command = '/app/bin/migrate'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000
