-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GetFiveApi.Enum.MatchTeam exposing (..)

import Json.Decode as Decode exposing (Decoder)


type MatchTeam
    = Team1
    | Team2


list : List MatchTeam
list =
    [ Team1, Team2 ]


decoder : Decoder MatchTeam
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "TEAM1" ->
                        Decode.succeed Team1

                    "TEAM2" ->
                        Decode.succeed Team2

                    _ ->
                        Decode.fail ("Invalid MatchTeam type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : MatchTeam -> String
toString enum____ =
    case enum____ of
        Team1 ->
            "TEAM1"

        Team2 ->
            "TEAM2"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe MatchTeam
fromString enumString____ =
    case enumString____ of
        "TEAM1" ->
            Just Team1

        "TEAM2" ->
            Just Team2

        _ ->
            Nothing
