-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GetFiveApi.Object exposing (..)


type GameServer
    = GameServer


type Match
    = Match


type Player
    = Player


type Team
    = Team
