-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GetFiveApi.Query exposing (..)

import GetFiveApi.InputObject
import GetFiveApi.Interface
import GetFiveApi.Object
import GetFiveApi.Scalar
import GetFiveApi.ScalarCodecs
import GetFiveApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


{-| Get all game server
-}
allGameServers :
    SelectionSet decodesTo GetFiveApi.Object.GameServer
    -> SelectionSet (List decodesTo) RootQuery
allGameServers object_ =
    Object.selectionForCompositeField "allGameServers" [] object_ (identity >> Decode.list)


{-| Get all matches
-}
allMatches :
    SelectionSet decodesTo GetFiveApi.Object.Match
    -> SelectionSet (List decodesTo) RootQuery
allMatches object_ =
    Object.selectionForCompositeField "allMatches" [] object_ (identity >> Decode.list)


{-| Get all teams
-}
allTeams :
    SelectionSet decodesTo GetFiveApi.Object.Team
    -> SelectionSet (List decodesTo) RootQuery
allTeams object_ =
    Object.selectionForCompositeField "allTeams" [] object_ (identity >> Decode.list)


type alias GameServerRequiredArguments =
    { id : GetFiveApi.ScalarCodecs.Id }


{-| Get a game server
-}
gameServer :
    GameServerRequiredArguments
    -> SelectionSet decodesTo GetFiveApi.Object.GameServer
    -> SelectionSet decodesTo RootQuery
gameServer requiredArgs object_ =
    Object.selectionForCompositeField "gameServer" [ Argument.required "id" requiredArgs.id (GetFiveApi.ScalarCodecs.codecs |> GetFiveApi.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias TeamRequiredArguments =
    { id : GetFiveApi.ScalarCodecs.Id }


{-| Get a game server
-}
team :
    TeamRequiredArguments
    -> SelectionSet decodesTo GetFiveApi.Object.Team
    -> SelectionSet decodesTo RootQuery
team requiredArgs object_ =
    Object.selectionForCompositeField "team" [ Argument.required "id" requiredArgs.id (GetFiveApi.ScalarCodecs.codecs |> GetFiveApi.Scalar.unwrapEncoder .codecId) ] object_ identity
