-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GetFiveApi.ScalarCodecs exposing (..)

import GetFiveApi.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    GetFiveApi.Scalar.Id


codecs : GetFiveApi.Scalar.Codecs Id
codecs =
    GetFiveApi.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
